let kioskStream=null,kioskFacing='user',kioskPhoto='';
function kioskStep(n){$('.kiosk-screen').addClass('d-none');$('#step-'+n).removeClass('d-none');$('.kiosk-step').removeClass('active').filter(function(){return Number($(this).data('step'))<=n}).addClass('active');if(n===2)kioskCamera();else kioskStop()}
async function kioskCamera(){kioskStop();try{kioskStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:kioskFacing},width:{ideal:1920},height:{ideal:1080}},audio:false});document.getElementById('video').srcObject=kioskStream}catch(e){swal('Camera access required','Browser settings me camera permission allow karein.','warning')}}
function kioskStop(){if(kioskStream){kioskStream.getTracks().forEach(t=>t.stop());kioskStream=null}}
$(function(){
 $('#employee_autocomplete').select2({width:'100%',placeholder:'Employee / Student search karein',minimumInputLength:2,ajax:{url:base_url+'Visitor/autocomplete',dataType:'json',delay:250,processResults:data=>({results:data}),cache:true}});
 $('#start-process').on('click',()=>kioskStep(2));$('#switch-camera').on('click',()=>{kioskFacing=kioskFacing==='user'?'environment':'user';kioskCamera()});
 $('#capture').on('click',()=>{const v=document.getElementById('video'),c=document.getElementById('canvas');if(!v.videoWidth)return swal('Camera ready hone dein');const scale=Math.min(1,1600/v.videoWidth);c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);c.getContext('2d').drawImage(v,0,0,c.width,c.height);kioskPhoto=c.toDataURL('image/jpeg',.9);$('#photo-preview,#detail-photo').attr('src',kioskPhoto).removeClass('d-none');$('#video,#capture').addClass('d-none');$('#retake').removeClass('d-none');$('#photo_base64').val(kioskPhoto);setTimeout(()=>kioskStep(3),450)});
 $('#retake,#back-to-photo').on('click',()=>{$('#photo-preview,#retake').addClass('d-none');$('#video,#capture').removeClass('d-none');kioskPhoto='';$('#photo_base64').val('');kioskStep(2)});
 $('.visitor-form').on('submit',function(e){e.preventDefault();if(!kioskPhoto)return swal('Photo required','Please capture your photo first.','warning');const btn=$('#save-visitor').prop('disabled',true);$.ajax({type:'POST',url:this.action,data:$(this).serialize(),dataType:'json'}).done(r=>{if(r.status!=='success')return swal(r.message||'Unable to save');$('#visitor_id').val(r.id);$('#enid').val(r.enid);$('#pass-name').text($('[name=guest_name]').val());$('#pass-host').text('Meeting: '+$('[name=employee]').val());$('#pass-photo').attr('src',kioskPhoto);$('#pass-status').text(r.approval_pending?'APPROVAL PENDING':'CHECKED IN').toggleClass('chip-expected',!!r.approval_pending);$('#qr-code').empty();new QRCode(document.getElementById('qr-code'),{text:base_url+'visitor/details/'+r.enid,width:125,height:125});kioskStep(4)}).fail(xhr=>swal(xhr.responseJSON?.message||'Server error')).always(()=>btn.prop('disabled',false))});
 $('#print-pass').on('click',()=>window.open(base_url+'visitor/details/'+$('#enid').val(),'_blank'));window.addEventListener('beforeunload',kioskStop);
});
